Repository 33otot/sb03-otboo-team03, pull requests merged in 2025-09, with the labels that each got.

#64 [S3] S3 파일 업로드 기능 구현
  build.gradle
  src/main/java/com/samsamotot/otboo/common/config/S3Config.java
  src/main/java/com/samsamotot/otboo/common/storage/S3ImageStorage.java
  src/main/resources/application-dev.yaml
  src/test/java/com/samsamotot/otboo/common/fixture/S3ImageFixture.java
  src/test/java/com/samsamotot/otboo/common/storage/S3ImageStorageTest.java
  src/test/resources/application-test.yaml
Labels: Feature

#66 [Clothes] 의상 속성 정의 등록 구현
  src/main/java/com/samsamotot/otboo/clothes/controller/ClothesAttributeDefApi.java
  src/main/java/com/samsamotot/otboo/clothes/controller/ClothesAttributeDefController.java
  src/main/java/com/samsamotot/otboo/clothes/dto/ClothesAttributeDefDto.java
  src/main/java/com/samsamotot/otboo/clothes/dto/request/ClothesAttributeDefCreateRequest.java
  src/main/java/com/samsamotot/otboo/clothes/entity/ClothesAttribute.java
  src/main/java/com/samsamotot/otboo/clothes/entity/ClothesAttributeDef.java
  src/main/java/com/samsamotot/otboo/clothes/entity/ClothesAttributeOption.java
  src/main/java/com/samsamotot/otboo/clothes/mapper/ClothesAttributeDefMapper.java
  src/main/java/com/samsamotot/otboo/clothes/repository/ClothesAttributeDefRepository.java
  src/main/java/com/samsamotot/otboo/clothes/service/ClothesAttributeDefService.java
  src/main/java/com/samsamotot/otboo/clothes/service/impl/ClothesAttributeDefServiceImpl.java
  src/main/java/com/samsamotot/otboo/common/exception/ErrorCode.java
  src/main/java/com/samsamotot/otboo/common/exception/clothes/definition/ClothesAttributeDefAlreadyExist.java
  src/main/java/com/samsamotot/otboo/common/exception/clothes/definition/ClothesAttributeDefException.java
  src/main/resources/schema.sql
  src/test/java/com/samsamotot/otboo/clothes/controller/ClothesAttributeDefControllerTest.java
  src/test/java/com/samsamotot/otboo/clothes/service/ClothesAttributeDefServiceTest.java
  src/test/java/com/samsamotot/otboo/common/fixture/ClothesAttributeDefFixture.java
Labels: Feature

#65 [Feed] 피드 목록 조회 기능
  build.gradle
  src/main/java/com/samsamotot/otboo/common/config/QueryDslConfig.java
  src/main/java/com/samsamotot/otboo/common/exception/ErrorCode.java
  src/main/java/com/samsamotot/otboo/feed/controller/FeedController.java
  src/main/java/com/samsamotot/otboo/feed/controller/api/FeedApi.java
  src/main/java/com/samsamotot/otboo/feed/dto/FeedCursorRequest.java
  src/main/java/com/samsamotot/otboo/feed/repository/FeedLikeRepository.java
  src/main/java/com/samsamotot/otboo/feed/repository/FeedRepository.java
  src/main/java/com/samsamotot/otboo/feed/repository/FeedRepositoryCustom.java
  src/main/java/com/samsamotot/otboo/feed/repository/FeedRepositoryImpl.java
  src/main/java/com/samsamotot/otboo/feed/service/FeedService.java
  src/main/java/com/samsamotot/otboo/feed/service/FeedServiceImpl.java
  src/main/java/com/samsamotot/otboo/location/entity/Location.java
  src/main/resources/application-dev.yaml
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/test/java/com/samsamotot/otboo/common/config/TestJpaAuditingConfig.java
  src/test/java/com/samsamotot/otboo/common/fixture/FeedFixture.java
  src/test/java/com/samsamotot/otboo/common/fixture/LocationFixture.java
  src/test/java/com/samsamotot/otboo/common/fixture/UserFixture.java
  src/test/java/com/samsamotot/otboo/common/fixture/WeatherFixture.java
  src/test/java/com/samsamotot/otboo/feed/controller/FeedControllerTest.java
  src/test/java/com/samsamotot/otboo/feed/repository/FeedRepositoryTest.java
  src/test/java/com/samsamotot/otboo/feed/service/FeedServiceTest.java
  src/test/java/com/samsamotot/otboo/follow/integration/FollowIntegrationTest.java
  src/test/resources/application-test.yaml
  src/test/resources/schema.sql
Labels: Feature

#68 [Feed] 피드 수정 기능
  src/main/java/com/samsamotot/otboo/common/exception/ErrorCode.java
  src/main/java/com/samsamotot/otboo/feed/controller/FeedController.java
  src/main/java/com/samsamotot/otboo/feed/controller/api/FeedApi.java
  src/main/java/com/samsamotot/otboo/feed/dto/FeedUpdateRequest.java
  src/main/java/com/samsamotot/otboo/feed/entity/Feed.java
  src/main/java/com/samsamotot/otboo/feed/repository/FeedLikeRepository.java
  src/main/java/com/samsamotot/otboo/feed/service/FeedService.java
  src/main/java/com/samsamotot/otboo/feed/service/FeedServiceImpl.java
  src/test/java/com/samsamotot/otboo/common/fixture/FeedFixture.java
  src/test/java/com/samsamotot/otboo/feed/controller/FeedControllerTest.java
  src/test/java/com/samsamotot/otboo/feed/service/FeedServiceTest.java
Labels: Feature

#75 [Follow] 팔로워 목록 조회 기능
  src/main/java/com/samsamotot/otboo/follow/controller/FollowController.java
  src/main/java/com/samsamotot/otboo/follow/mapper/FollowMapper.java
  src/main/java/com/samsamotot/otboo/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/samsamotot/otboo/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/samsamotot/otboo/follow/service/FollowService.java
  src/main/java/com/samsamotot/otboo/follow/service/FollowServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/test/java/com/samsamotot/otboo/follow/controller/FollowControllerTest.java
  src/test/java/com/samsamotot/otboo/follow/integration/FollowIntegrationTest.java
  src/test/java/com/samsamotot/otboo/follow/repository/FollowRepositoryImplTest.java
  src/test/java/com/samsamotot/otboo/follow/service/FollowServiceImplTest.java
Labels: Feature

#76 [Clothes] 의상 속성 정의 수정 구현
  src/main/java/com/samsamotot/otboo/clothes/controller/ClothesAttributeDefApi.java
  src/main/java/com/samsamotot/otboo/clothes/controller/ClothesAttributeDefController.java
  src/main/java/com/samsamotot/otboo/clothes/dto/request/ClothesAttributeDefUpdateRequest.java
  src/main/java/com/samsamotot/otboo/clothes/entity/ClothesAttributeDef.java
  src/main/java/com/samsamotot/otboo/clothes/service/ClothesAttributeDefService.java
  src/main/java/com/samsamotot/otboo/clothes/service/impl/ClothesAttributeDefServiceImpl.java
  src/main/java/com/samsamotot/otboo/common/exception/ErrorCode.java
  src/main/java/com/samsamotot/otboo/common/exception/clothes/definition/ClothesAttributeDefAlreadyExist.java
  src/main/java/com/samsamotot/otboo/common/exception/clothes/definition/ClothesAttributeDefAlreadyExistException.java
  src/main/java/com/samsamotot/otboo/common/exception/clothes/definition/ClothesAttributeDefNotFoundException.java
  src/test/java/com/samsamotot/otboo/clothes/controller/ClothesAttributeDefControllerTest.java
  src/test/java/com/samsamotot/otboo/clothes/service/ClothesAttributeDefServiceTest.java
  src/test/java/com/samsamotot/otboo/common/fixture/ClothesAttributeDefFixture.java
Labels: Feature

#81 [Follow] 팔로우 요약 정보 조회 기능
  src/main/java/com/samsamotot/otboo/follow/controller/FollowController.java
  src/main/java/com/samsamotot/otboo/follow/dto/FollowSummaryDto.java
  src/main/java/com/samsamotot/otboo/follow/repository/FollowRepository.java
  src/main/java/com/samsamotot/otboo/follow/service/FollowService.java
  src/main/java/com/samsamotot/otboo/follow/service/FollowServiceImpl.java
  src/test/java/com/samsamotot/otboo/follow/controller/FollowControllerTest.java
  src/test/java/com/samsamotot/otboo/follow/integration/FollowIntegrationTest.java
  src/test/java/com/samsamotot/otboo/follow/service/FollowServiceImplTest.java
Labels: Feature

#80 [Clothes] 의상 속성 정의 목록 조회 구현
  src/main/java/com/samsamotot/otboo/clothes/controller/ClothesAttributeDefApi.java
  src/main/java/com/samsamotot/otboo/clothes/controller/ClothesAttributeDefController.java
  src/main/java/com/samsamotot/otboo/clothes/repository/ClothesAttributeDefRepository.java
  src/main/java/com/samsamotot/otboo/clothes/service/ClothesAttributeDefService.java
  src/main/java/com/samsamotot/otboo/clothes/service/impl/ClothesAttributeDefServiceImpl.java
  src/test/java/com/samsamotot/otboo/clothes/controller/ClothesAttributeDefControllerTest.java
  src/test/java/com/samsamotot/otboo/clothes/service/ClothesAttributeDefServiceTest.java
Labels: Feature

#86 [Clothes] 의상 등록 기능 구현
  src/main/java/com/samsamotot/otboo/clothes/controller/ClothesAttributeDefApi.java
  src/main/java/com/samsamotot/otboo/clothes/controller/ClothesController.java
  src/main/java/com/samsamotot/otboo/clothes/controller/ClothesControllerApi.java
  src/main/java/com/samsamotot/otboo/clothes/dto/ClothesAttributeDto.java
  src/main/java/com/samsamotot/otboo/clothes/dto/request/ClothesCreateRequest.java
  src/main/java/com/samsamotot/otboo/clothes/dto/request/ClothesDto.java
  src/main/java/com/samsamotot/otboo/clothes/entity/Clothes.java
  src/main/java/com/samsamotot/otboo/clothes/exception/ClothesException.java
  src/main/java/com/samsamotot/otboo/clothes/exception/definition/ClothesAttributeDefAlreadyExistException.java
  src/main/java/com/samsamotot/otboo/clothes/exception/definition/ClothesAttributeDefException.java
  src/main/java/com/samsamotot/otboo/clothes/exception/definition/ClothesAttributeDefNotFoundException.java
  src/main/java/com/samsamotot/otboo/clothes/service/ClothesService.java
  src/main/java/com/samsamotot/otboo/clothes/service/impl/ClothesAttributeDefServiceImpl.java
  src/main/java/com/samsamotot/otboo/clothes/service/impl/ClothesServiceImpl.java
  src/test/java/com/samsamotot/otboo/clothes/controller/ClothesControllerTest.java
  src/test/java/com/samsamotot/otboo/clothes/service/ClothesAttributeDefServiceTest.java
  src/test/java/com/samsamotot/otboo/clothes/service/ClothesServiceTest.java
Labels: Feature

#87 [USER] 사용자 로그인 및 로그아웃
  Docker-Compose.yml
  build.gradle
  src/main/java/com/samsamotot/otboo/auth/controller/AuthController.java
  src/main/java/com/samsamotot/otboo/auth/dto/LoginRequest.java
  src/main/java/com/samsamotot/otboo/auth/service/AuthService.java
  src/main/java/com/samsamotot/otboo/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/samsamotot/otboo/common/config/SecurityProperties.java
  src/main/java/com/samsamotot/otboo/common/exception/GlobalExceptionHandler.java
  src/main/java/com/samsamotot/otboo/common/security/config/SecurityConfig.java
  src/main/java/com/samsamotot/otboo/common/security/csrf/CsrfTokenService.java
  src/main/java/com/samsamotot/otboo/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/samsamotot/otboo/common/security/jwt/JwtDto.java
  src/main/java/com/samsamotot/otboo/common/security/jwt/JwtTokenProvider.java
  src/main/java/com/samsamotot/otboo/common/security/service/CustomUserDetails.java
  src/main/java/com/samsamotot/otboo/user/service/UserService.java
  src/main/java/com/samsamotot/otboo/user/service/impl/UserServiceImpl.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/logback-spring.xml
  src/test/java/com/samsamotot/otboo/auth/controller/AuthControllerTest.java
  src/test/java/com/samsamotot/otboo/auth/service/AuthServiceImplTest.java
  src/test/java/com/samsamotot/otboo/comment/repository/CommentRepositoryTest.java
  src/test/resources/application-test.yaml
Labels: Feature

#88 [Feed] 피드 관련 API Spring Security(Principal) 기반 전환
  .github/workflows/ci.yml
  src/main/java/com/samsamotot/otboo/common/security/config/SecurityConfig.java
  src/main/java/com/samsamotot/otboo/common/security/csrf/SpaCsrfTokenRequestHandler.java
  src/main/java/com/samsamotot/otboo/common/util/AuthUtil.java
  src/main/java/com/samsamotot/otboo/feed/controller/FeedController.java
  src/main/java/com/samsamotot/otboo/feed/controller/FeedLikeController.java
  src/main/java/com/samsamotot/otboo/feed/controller/api/FeedApi.java
  src/main/java/com/samsamotot/otboo/feed/controller/api/FeedLikeApi.java
  src/main/resources/static/assets/index-4upUhzSi.css
  src/main/resources/static/assets/index-BDHebkH-.js
  src/main/resources/static/assets/index-BaIKQabd.js
  src/main/resources/static/assets/index-BogyKWzh.css
  src/main/resources/static/index.html
  src/test/java/com/samsamotot/otboo/comment/repository/CommentRepositoryTest.java
  src/test/java/com/samsamotot/otboo/common/config/SecurityTestConfig.java
  src/test/java/com/samsamotot/otboo/feed/controller/FeedControllerTest.java
  src/test/java/com/samsamotot/otboo/feed/controller/FeedLikeControllerTest.java
Labels: Refactor

#92 [Feed] 피드 좋아요, 좋아요 취소, 댓글 작성시 피드의 좋아요수, 댓글 수가 업데이트 되지 않았던 버그 수정
  src/main/java/com/samsamotot/otboo/comment/service/CommentServiceImpl.java
  src/main/java/com/samsamotot/otboo/common/util/AuthUtil.java
  src/main/java/com/samsamotot/otboo/feed/controller/FeedController.java
  src/main/java/com/samsamotot/otboo/feed/controller/FeedLikeController.java
  src/main/java/com/samsamotot/otboo/feed/controller/api/FeedApi.java
  src/main/java/com/samsamotot/otboo/feed/controller/api/FeedLikeApi.java
  src/main/java/com/samsamotot/otboo/feed/repository/FeedRepository.java
  src/main/java/com/samsamotot/otboo/feed/service/FeedLikeServiceImpl.java
  src/test/java/com/samsamotot/otboo/comment/service/CommentServiceTest.java
  src/test/java/com/samsamotot/otboo/feed/service/FeedLikeServiceTest.java
Labels: bug

#95 [Follow/DM] TODO 변경 예정사항 수정
  src/main/java/com/samsamotot/otboo/directmessage/controller/DirectMessageController.java
  src/main/java/com/samsamotot/otboo/directmessage/controller/api/DirectMessageApi.java
  src/main/java/com/samsamotot/otboo/directmessage/service/DirectMessageServiceImpl.java
  src/main/java/com/samsamotot/otboo/follow/controller/FollowController.java
  src/main/java/com/samsamotot/otboo/follow/service/FollowServiceImpl.java
  src/test/java/com/samsamotot/otboo/directmessage/service/DirectMessageServiceImplTest.java
  src/test/java/com/samsamotot/otboo/follow/service/FollowServiceImplTest.java
Labels: Refactor

#96 [USER] csrf token 조회 및 재발급
  src/main/java/com/samsamotot/otboo/auth/controller/AuthController.java
  src/main/java/com/samsamotot/otboo/common/exception/GlobalExceptionHandler.java
  src/main/java/com/samsamotot/otboo/common/security/config/SecurityConfig.java
  src/main/java/com/samsamotot/otboo/common/security/csrf/CsrfController.java
  src/test/java/com/samsamotot/otboo/common/security/csrf/CsrfControllerTest.java
Labels: Feature

#101 [기타] Docker 환경 구성 v2 (redis)
  Docker-Compose.yml
  src/main/java/com/samsamotot/otboo/common/config/RedisConfig.java
  src/main/resources/application.yaml
Labels: Config

#102 [Weather] 날씨 정보 조회 로직 추가
  Docker-Compose.yml
  build.gradle
  src/main/java/com/samsamotot/otboo/common/config/WebClientConfig.java
  src/main/java/com/samsamotot/otboo/common/exception/ErrorCode.java
  src/main/java/com/samsamotot/otboo/feed/repository/FeedRepository.java
  src/main/java/com/samsamotot/otboo/location/repository/LocationRepository.java
  src/main/java/com/samsamotot/otboo/location/service/impl/LocationServiceImpl.java
  src/main/java/com/samsamotot/otboo/weather/client/KmaClient.java
  src/main/java/com/samsamotot/otboo/weather/config/DataLoader.java
  src/main/java/com/samsamotot/otboo/weather/config/batch/WeatherBatchTasklet.java
  src/main/java/com/samsamotot/otboo/weather/controller/WeatherController.java
  src/main/java/com/samsamotot/otboo/weather/controller/api/WeatherApi.java
  src/main/java/com/samsamotot/otboo/weather/dto/WeatherAPILocation.java
  src/main/java/com/samsamotot/otboo/weather/entity/Weather.java
  src/main/java/com/samsamotot/otboo/weather/mapper/WeatherMapper.java
  src/main/java/com/samsamotot/otboo/weather/repository/WeatherRepository.java
  src/main/java/com/samsamotot/otboo/weather/service/WeatherService.java
  src/main/java/com/samsamotot/otboo/weather/service/WeatherTransactionService.java
  src/main/java/com/samsamotot/otboo/weather/service/impl/WeatherServiceImpl.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/main/resources/data.sql
  src/main/resources/locations_korea.csv
  src/test/java/com/samsamotot/otboo/common/fixture/WeatherFixture.java
  src/test/java/com/samsamotot/otboo/location/integration/LocationIntegrationTest.java
  src/test/java/com/samsamotot/otboo/weather/controller/WeatherControllerSliceTest.java
  src/test/java/com/samsamotot/otboo/weather/controller/WeatherControllerTest.java
  src/test/java/com/samsamotot/otboo/weather/service/WeatherServiceImplTest.java
Labels: Feature, Refactor

#105 [Clothes] 의상 속성 관리 권한 적용
  src/main/java/com/samsamotot/otboo/clothes/service/impl/ClothesAttributeDefServiceImpl.java
  src/main/java/com/samsamotot/otboo/common/security/config/SecurityConfig.java
  src/test/java/com/samsamotot/otboo/clothes/controller/ClothesAttributeDefControllerSecurityTest.java
Labels: Feature, Refactor

#108 [Weather] 날씨 조회 로직 리팩토링
  src/main/java/com/samsamotot/otboo/common/config/WebClientConfig.java
  src/main/java/com/samsamotot/otboo/common/exception/ErrorCode.java
  src/main/java/com/samsamotot/otboo/location/entity/Location.java
  src/main/java/com/samsamotot/otboo/location/repository/LocationRepository.java
  src/main/java/com/samsamotot/otboo/location/service/LocationService.java
  src/main/java/com/samsamotot/otboo/location/service/impl/LocationServiceImpl.java
  src/main/java/com/samsamotot/otboo/profile/repository/ProfileRepository.java
  src/main/java/com/samsamotot/otboo/profile/service/impl/ProfileServiceImpl.java
  src/main/java/com/samsamotot/otboo/weather/client/KmaClient.java
  src/main/java/com/samsamotot/otboo/weather/config/DataLoader.java
  src/main/java/com/samsamotot/otboo/weather/config/batch/WeatherBatchTasklet.java
  src/main/java/com/samsamotot/otboo/weather/controller/WeatherController.java
  src/main/java/com/samsamotot/otboo/weather/mapper/WeatherMapper.java
  src/main/java/com/samsamotot/otboo/weather/service/impl/WeatherServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/test/java/com/samsamotot/otboo/common/fixture/ProfileFixture.java
  src/test/java/com/samsamotot/otboo/location/service/LocationServiceImplTest.java
  src/test/java/com/samsamotot/otboo/profile/controller/UserProfileControllerTest.java
  src/test/java/com/samsamotot/otboo/weather/service/WeatherServiceImplTest.java
Labels: Refactor
