Repository 33otot/sb03-otboo-team03, pull requests merged in 2025-10, with the labels that each got.

#112 [Recommendation] 의상 추천 기능
  src/main/java/com/samsamotot/otboo/clothes/mapper/ClothesMapper.java
  src/main/java/com/samsamotot/otboo/clothes/repository/ClothesRepository.java
  src/main/java/com/samsamotot/otboo/profile/repository/ProfileRepository.java
  src/main/java/com/samsamotot/otboo/recommendation/controller/RecommendationController.java
  src/main/java/com/samsamotot/otboo/recommendation/controller/api/RecommendationApi.java
  src/main/java/com/samsamotot/otboo/recommendation/dto/RecommendationContextDto.java
  src/main/java/com/samsamotot/otboo/recommendation/dto/RecommendationDto.java
  src/main/java/com/samsamotot/otboo/recommendation/service/ItemSelectorEngine.java
  src/main/java/com/samsamotot/otboo/recommendation/service/RecommendationService.java
  src/main/java/com/samsamotot/otboo/recommendation/service/RecommendationServiceImpl.java
  src/main/java/com/samsamotot/otboo/recommendation/type/RecommendationAttribute.java
  src/main/java/com/samsamotot/otboo/recommendation/type/Season.java
  src/main/java/com/samsamotot/otboo/recommendation/type/Style.java
  src/main/java/com/samsamotot/otboo/recommendation/type/Thickness.java
  src/main/java/com/samsamotot/otboo/recommendation/type/Waterproof.java
  src/main/resources/application.yaml
  src/main/resources/data.sql
  src/main/resources/static/assets/index-UUTHrOpk.js
  src/main/resources/static/index.html
  src/test/java/com/samsamotot/otboo/common/fixture/ClothesFixture.java
  src/test/java/com/samsamotot/otboo/common/fixture/ProfileFixture.java
  src/test/java/com/samsamotot/otboo/common/fixture/WeatherFixture.java
  src/test/java/com/samsamotot/otboo/recommendation/controller/RecommendationControllerTest.java
  src/test/java/com/samsamotot/otboo/recommendation/service/ItemSelectorEngineTest.java
  src/test/java/com/samsamotot/otboo/recommendation/service/RecommendationServiceTest.java
Labels: Feature

#104 [USER] 계정 목록 조회
  src/main/java/com/samsamotot/otboo/user/controller/UserController.java
  src/main/java/com/samsamotot/otboo/user/controller/api/UserApi.java
  src/main/java/com/samsamotot/otboo/user/dto/UserDtoCursorResponse.java
  src/main/java/com/samsamotot/otboo/user/dto/UserListRequest.java
  src/main/java/com/samsamotot/otboo/user/repository/UserRepository.java
  src/main/java/com/samsamotot/otboo/user/repository/custom/UserRepositoryCustom.java
  src/main/java/com/samsamotot/otboo/user/repository/custom/UserRepositoryCustomImpl.java
  src/main/java/com/samsamotot/otboo/user/service/UserService.java
  src/main/java/com/samsamotot/otboo/user/service/impl/UserServiceImpl.java
  src/test/java/com/samsamotot/otboo/user/controller/UserControllerTest.java
  src/test/java/com/samsamotot/otboo/user/service/UserServiceTest.java
Labels: Feature

#118 [기타] Docker 환경 구성 v3 (kafka + nginx)
  Makefile
  README.md
  docker-compose.local.yml
  docker-compose.prod.yml
  docker-compose.yml
  nginx/Dockerfile
  nginx/conf/default.conf
  src/main/resources/application.yaml
  src/main/resources/data.sql
Labels: Config

#123 [Weather] 특별한 날씨 변화 감지 시 알림 전송
  src/main/java/com/samsamotot/otboo/profile/repository/ProfileRepository.java
  src/main/java/com/samsamotot/otboo/weather/config/batch/WeatherBatchTasklet.java
  src/main/java/com/samsamotot/otboo/weather/dto/WeatherAlterType.java
  src/main/java/com/samsamotot/otboo/weather/dto/WeatherChangeDto.java
  src/main/java/com/samsamotot/otboo/weather/repository/WeatherRepository.java
  src/main/java/com/samsamotot/otboo/weather/service/WeatherAlterService.java
  src/main/java/com/samsamotot/otboo/weather/service/WeatherService.java
  src/main/java/com/samsamotot/otboo/weather/service/WeatherTransactionService.java
  src/main/java/com/samsamotot/otboo/weather/service/impl/WeatherAlterServiceImpl.java
  src/main/java/com/samsamotot/otboo/weather/service/impl/WeatherServiceImpl.java
  src/test/java/com/samsamotot/otboo/common/fixture/ProfileFixture.java
  src/test/java/com/samsamotot/otboo/common/fixture/WeatherFixture.java
  src/test/java/com/samsamotot/otboo/weather/service/WeatherAlterServiceTest.java
  src/test/java/com/samsamotot/otboo/weather/service/WeatherServiceImplTest.java
Labels: Feature

#125 [Deploy] aws 배포 및 CD
  .github/workflows/cd.yml
  Dockerfile
  build.gradle
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
  src/main/resources/data.sql
  src/main/resources/logback-spring.xml
Labels: Feature, Deployment

#131 [Deploy] 결과 변수 읽지 못해 CD 단계 실패하는 문제 개선
  .github/workflows/cd.yml
Labels: bug
